Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_version = "20170313.0.7"
    config.vm.provision "shell",
        path: "create_environment.sh"
	config.vm.provision "shell", inline: <<-SHELL
			defaults="/etc/ros/rosdep/sources.list.d/20-default.list"
			if [ -f $defaults ] ; then
				rm -rf $defaults
			fi
			rosdep init
			rosdep fix-permissions
		SHELL
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
			rosdep update
		SHELL
    config.vm.synced_folder "../../Autoware", "/Autoware"
	
	config.vm.provider "virtualbox" do |vb|
		# Customize the amount of memory on the VM:
		vb.memory = "4096"
		# Add ntp demon, since we will be sharing files with Windows hosts
		config.vm.provision "shell", inline: <<-SHELL
			sudo apt-get install ntp
		SHELL
	end
end
